2021/11/08 10:38:08 AM - uvicorn.error - INFO - Shutting down
2021/11/08 10:38:08 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:38:08 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:38:08 AM - uvicorn.error - INFO - Finished server process [3090]
2021/11/08 10:39:50 AM - uvicorn.error - INFO - Started server process [4133]
2021/11/08 10:39:50 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:39:50 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:40:02 AM - Rede1Minuto Server - INFO - Consulta da disponibilidade de Portas em Locker
2021/11/08 10:40:02 AM - Rede1Minuto Server - INFO - e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/08 10:40:04 AM - Rede1Minuto Server - ERROR - (<class 'sqlalchemy.exc.ProgrammingError'>, ProgrammingError('(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'\'2021-11-08 10:40:04\'\',\\n                                    1,  \\n            ...\' at line 19")'), <traceback object at 0x7f14adf5f400>)
2021/11/08 10:40:04 AM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'traceback' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/08 10:41:35 AM - uvicorn.error - INFO - Shutting down
2021/11/08 10:41:35 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:41:35 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:41:35 AM - uvicorn.error - INFO - Finished server process [4133]
2021/11/08 10:41:38 AM - uvicorn.error - INFO - Started server process [4144]
2021/11/08 10:41:38 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:41:38 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:41:46 AM - Rede1Minuto Server - INFO - Consulta da disponibilidade de Portas em Locker
2021/11/08 10:41:46 AM - Rede1Minuto Server - INFO - e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/08 10:41:48 AM - Rede1Minuto Server - INFO - INSERT INTO `rede1minuto`.`reserva_simples`
                                    (`IdTransacaoUnica`,
                                    `IdSolicitante`,
                                    `IdReferencia`,
                                    `idRede`,
                                    `idLocker`,
                                    `idLockerPorta`,
                                    `DataHoraSolicitacao`,
                                    `idStatusReserva`,
                                    `idServicoReserva`,
                                    `TipoFluxoAtual`)
                                VALUES
                                    (9e20183e-4099-11ec-b64b-00155df485d9,
                                    12023895000169,
                                    1455444,
                                    1,
                                    5d00e429-32a8-11ec-9da0-5cc9d363c015,
                                    46033f6a-3358-11ec-a53d-5cc9d363c015,
                                    '2021-11-08 10:41:48'',
                                    1,  
                                    5,  
                                    0);
2021/11/08 10:41:48 AM - Rede1Minuto Server - ERROR - (<class 'sqlalchemy.exc.DataError'>, DataError('(pymysql.err.DataError) (1367, "Illegal double \'9e20183\' value found during parsing")'), <traceback object at 0x7fa8076aee40>)
2021/11/08 10:41:48 AM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'traceback' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/08 10:43:19 AM - uvicorn.error - INFO - Shutting down
2021/11/08 10:43:19 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:43:19 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:43:19 AM - uvicorn.error - INFO - Finished server process [4144]
2021/11/08 10:43:22 AM - uvicorn.error - INFO - Started server process [4532]
2021/11/08 10:43:22 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:43:22 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:43:39 AM - Rede1Minuto Server - INFO - Consulta da disponibilidade de Portas em Locker
2021/11/08 10:43:39 AM - Rede1Minuto Server - INFO - e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/08 10:43:41 AM - Rede1Minuto Server - INFO - INSERT INTO `rede1minuto`.`reserva_simples`
                                    (`IdTransacaoUnica`,
                                    `IdSolicitante`,
                                    `IdReferencia`,
                                    `idRede`,
                                    `idLocker`,
                                    `idLockerPorta`,
                                    `DataHoraSolicitacao`,
                                    `idStatusReserva`,
                                    `idServicoReserva`,
                                    `TipoFluxoAtual`)
                                VALUES
                                    ('e1a54a34-4099-11ec-bf5f-00155df485d9',
                                    '12023895000169',
                                    '1455444',
                                    1,
                                    '5d00e429-32a8-11ec-9da0-5cc9d363c015',
                                    '46270291-3358-11ec-8ba4-5cc9d363c015',
                                    '2021-11-08 10:43:41'',
                                    1,  
                                    5,  
                                    0);
2021/11/08 10:43:41 AM - Rede1Minuto Server - ERROR - (<class 'sqlalchemy.exc.ProgrammingError'>, ProgrammingError('(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'\'2021-11-08 10:43:41\'\',\\n                                    1,  \\n            ...\' at line 19")'), <traceback object at 0x7f6b93ceee80>)
2021/11/08 10:43:41 AM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'traceback' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/08 10:44:13 AM - uvicorn.error - INFO - Shutting down
2021/11/08 10:44:13 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:44:13 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:44:13 AM - uvicorn.error - INFO - Finished server process [4532]
2021/11/08 10:44:15 AM - uvicorn.error - INFO - Started server process [4542]
2021/11/08 10:44:15 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:44:15 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:44:21 AM - Rede1Minuto Server - INFO - Consulta da disponibilidade de Portas em Locker
2021/11/08 10:44:21 AM - Rede1Minuto Server - INFO - e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/08 10:44:23 AM - Rede1Minuto Server - INFO - INSERT INTO `rede1minuto`.`reserva_simples`
                                    (`IdTransacaoUnica`,
                                    `IdSolicitante`,
                                    `IdReferencia`,
                                    `idRede`,
                                    `idLocker`,
                                    `idLockerPorta`,
                                    `DataHoraSolicitacao`,
                                    `idStatusReserva`,
                                    `idServicoReserva`,
                                    `TipoFluxoAtual`)
                                VALUES
                                    ('fa878094-4099-11ec-a223-00155df485d9',
                                    '12023895000169',
                                    '1455444',
                                    1,
                                    '5d00e429-32a8-11ec-9da0-5cc9d363c015',
                                    '464ad489-3358-11ec-9c71-5cc9d363c015',
                                    '2021-11-08 10:44:23',
                                    1,  
                                    5,  
                                    0);
2021/11/08 10:44:23 AM - pika.adapters.utils.connection_workflow - INFO - Pika version 1.2.0 connecting to ('167.71.26.87', 5672)
2021/11/08 10:44:23 AM - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51108), raddr=('167.71.26.87', 5672)>
2021/11/08 10:44:23 AM - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f005bc41eb0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f005bc41eb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>).
2021/11/08 10:44:24 AM - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f005bc41eb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 10:44:24 AM - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f005bc41eb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 10:44:24 AM - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f005bc41eb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 10:44:24 AM - pika.adapters.blocking_connection - INFO - Created channel=1
2021/11/08 10:44:24 AM - pika.adapters.blocking_connection - INFO - Closing connection (200): Normal shutdown
2021/11/08 10:44:24 AM - pika.channel - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f005bc41eb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 10:44:24 AM - pika.channel - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f005bc41eb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 10:44:24 AM - pika.connection - INFO - Closing connection (200): 'Normal shutdown'
2021/11/08 10:44:24 AM - pika.adapters.utils.io_services_utils - INFO - Aborting transport connection: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51108), raddr=('167.71.26.87', 5672)>
2021/11/08 10:44:24 AM - pika.adapters.utils.io_services_utils - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51108), raddr=('167.71.26.87', 5672)>
2021/11/08 10:44:24 AM - pika.adapters.utils.io_services_utils - INFO - Deactivating transport: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51108), raddr=('167.71.26.87', 5672)>
2021/11/08 10:44:24 AM - pika.connection - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 10:44:24 AM - pika.connection - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 10:44:24 AM - pika.adapters.utils.io_services_utils - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51108), raddr=('167.71.26.87', 5672)>
2021/11/08 10:44:24 AM - pika.adapters.blocking_connection - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2021/11/08 10:51:57 AM - uvicorn.error - INFO - Shutting down
2021/11/08 10:51:57 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:51:57 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:51:57 AM - uvicorn.error - INFO - Finished server process [4542]
2021/11/08 10:52:00 AM - uvicorn.error - INFO - Started server process [5689]
2021/11/08 10:52:00 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:52:00 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:52:12 AM - Rede1Minuto Server - INFO - Consulta da disponibilidade de Portas em Locker
2021/11/08 10:52:12 AM - Rede1Minuto Server - INFO - e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/08 10:52:13 AM - Rede1Minuto Server - ERROR - (<class 'AttributeError'>, AttributeError("'Connection' object has no attribute 'commit'"), <traceback object at 0x7f853d514500>)
2021/11/08 10:52:13 AM - Rede1Minuto Server - ERROR - (<class 'AttributeError'>, AttributeError("'Connection' object has no attribute 'commit'"), <traceback object at 0x7f853d393900>)
2021/11/08 10:52:13 AM - Rede1Minuto Server - ERROR - (<class 'AttributeError'>, AttributeError("'Connection' object has no attribute 'commit'"), <traceback object at 0x7f853d32e980>)
2021/11/08 10:52:14 AM - Rede1Minuto Server - ERROR - (<class 'AttributeError'>, AttributeError("'Connection' object has no attribute 'commit'"), <traceback object at 0x7f853d32ecc0>)
2021/11/08 10:52:14 AM - pika.adapters.utils.connection_workflow - INFO - Pika version 1.2.0 connecting to ('167.71.26.87', 5672)
2021/11/08 10:52:14 AM - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51118), raddr=('167.71.26.87', 5672)>
2021/11/08 10:52:14 AM - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f853d33feb0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f853d33feb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>).
2021/11/08 10:52:15 AM - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f853d33feb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 10:52:15 AM - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f853d33feb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 10:52:15 AM - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f853d33feb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 10:52:15 AM - pika.adapters.blocking_connection - INFO - Created channel=1
2021/11/08 10:52:15 AM - pika.adapters.blocking_connection - INFO - Closing connection (200): Normal shutdown
2021/11/08 10:52:15 AM - pika.channel - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f853d33feb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 10:52:15 AM - pika.channel - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f853d33feb0> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 10:52:15 AM - pika.connection - INFO - Closing connection (200): 'Normal shutdown'
2021/11/08 10:52:15 AM - pika.adapters.utils.io_services_utils - INFO - Aborting transport connection: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51118), raddr=('167.71.26.87', 5672)>
2021/11/08 10:52:15 AM - pika.adapters.utils.io_services_utils - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51118), raddr=('167.71.26.87', 5672)>
2021/11/08 10:52:15 AM - pika.adapters.utils.io_services_utils - INFO - Deactivating transport: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51118), raddr=('167.71.26.87', 5672)>
2021/11/08 10:52:15 AM - pika.connection - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 10:52:15 AM - pika.connection - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 10:52:15 AM - pika.adapters.utils.io_services_utils - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.166.210', 51118), raddr=('167.71.26.87', 5672)>
2021/11/08 10:52:15 AM - pika.adapters.blocking_connection - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2021/11/08 11:20:28 AM - uvicorn.error - INFO - Shutting down
2021/11/08 11:20:29 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 11:20:29 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 11:20:29 AM - uvicorn.error - INFO - Finished server process [5689]
2021/11/08 11:20:31 AM - uvicorn.error - INFO - Started server process [6075]
2021/11/08 11:20:31 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 11:20:31 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 11:36:27 AM - uvicorn.error - INFO - Shutting down
2021/11/08 11:36:27 AM - uvicorn.error - INFO - Waiting for connections to close. (CTRL+C to force quit)
2021/11/08 11:36:27 AM - uvicorn.error - INFO - Finished server process [6075]
2021/11/08 11:43:16 AM - uvicorn.error - INFO - Started server process [67]
2021/11/08 11:43:16 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 11:43:16 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 11:44:12 AM - Rede1Minuto Server - INFO - Consulta da disponibilidade de Portas em Locker
2021/11/08 11:44:12 AM - Rede1Minuto Server - INFO - e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/08 11:44:14 AM - pika.adapters.utils.connection_workflow - INFO - Pika version 1.2.0 connecting to ('167.71.26.87', 5672)
2021/11/08 11:44:15 AM - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38198), raddr=('167.71.26.87', 5672)>
2021/11/08 11:44:15 AM - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f500fc1ee20>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f500fc1ee20> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>).
2021/11/08 11:44:15 AM - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f500fc1ee20> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 11:44:15 AM - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f500fc1ee20> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 11:44:15 AM - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f500fc1ee20> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 11:44:15 AM - pika.adapters.blocking_connection - INFO - Created channel=1
2021/11/08 11:44:15 AM - pika.adapters.blocking_connection - INFO - Closing connection (200): Normal shutdown
2021/11/08 11:44:15 AM - pika.channel - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f500fc1ee20> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 11:44:15 AM - pika.channel - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f500fc1ee20> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 11:44:15 AM - pika.connection - INFO - Closing connection (200): 'Normal shutdown'
2021/11/08 11:44:15 AM - pika.adapters.utils.io_services_utils - INFO - Aborting transport connection: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38198), raddr=('167.71.26.87', 5672)>
2021/11/08 11:44:15 AM - pika.adapters.utils.io_services_utils - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38198), raddr=('167.71.26.87', 5672)>
2021/11/08 11:44:15 AM - pika.adapters.utils.io_services_utils - INFO - Deactivating transport: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38198), raddr=('167.71.26.87', 5672)>
2021/11/08 11:44:15 AM - pika.connection - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 11:44:15 AM - pika.connection - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 11:44:15 AM - pika.adapters.utils.io_services_utils - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38198), raddr=('167.71.26.87', 5672)>
2021/11/08 11:44:15 AM - pika.adapters.blocking_connection - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2021/11/08 11:44:59 AM - uvicorn.error - INFO - Shutting down
2021/11/08 11:44:59 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 11:44:59 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 11:44:59 AM - uvicorn.error - INFO - Finished server process [67]
2021/11/08 11:45:02 AM - uvicorn.error - INFO - Started server process [667]
2021/11/08 11:45:02 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 11:45:02 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 11:45:39 AM - uvicorn.error - INFO - Shutting down
2021/11/08 11:45:39 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 11:45:39 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 11:45:39 AM - uvicorn.error - INFO - Finished server process [667]
2021/11/08 11:45:42 AM - uvicorn.error - INFO - Started server process [1269]
2021/11/08 11:45:42 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 11:45:42 AM - uvicorn.error - INFO - Application startup complete.
2021/11/08 02:40:17 PM - uvicorn.error - INFO - Shutting down
2021/11/08 02:40:17 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 02:40:17 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 02:40:17 PM - uvicorn.error - INFO - Finished server process [1269]
2021/11/08 02:40:24 PM - uvicorn.error - INFO - Started server process [14832]
2021/11/08 02:40:24 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 02:40:24 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 02:58:45 PM - uvicorn.error - INFO - Shutting down
2021/11/08 02:58:46 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 02:58:46 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 02:58:46 PM - uvicorn.error - INFO - Finished server process [14832]
2021/11/08 03:03:47 PM - uvicorn.error - INFO - Started server process [16206]
2021/11/08 03:03:47 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 03:03:47 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 03:06:56 PM - uvicorn.error - INFO - Shutting down
2021/11/08 03:06:57 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 03:06:57 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 03:06:57 PM - uvicorn.error - INFO - Finished server process [16206]
2021/11/08 03:06:59 PM - uvicorn.error - INFO - Started server process [16581]
2021/11/08 03:06:59 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 03:06:59 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 03:07:58 PM - Rede1Minuto Server - INFO - Consulta da disponibilidade de Portas em Locker
2021/11/08 03:07:58 PM - Rede1Minuto Server - INFO - e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/08 03:08:00 PM - pika.adapters.utils.connection_workflow - INFO - Pika version 1.2.0 connecting to ('167.71.26.87', 5672)
2021/11/08 03:08:00 PM - pika.adapters.utils.io_services_utils - INFO - Socket connected: <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38232), raddr=('167.71.26.87', 5672)>
2021/11/08 03:08:00 PM - pika.adapters.utils.connection_workflow - INFO - Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8a406d3f40>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8a406d3f40> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>).
2021/11/08 03:08:01 PM - pika.adapters.utils.connection_workflow - INFO - AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8a406d3f40> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 03:08:01 PM - pika.adapters.utils.connection_workflow - INFO - AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8a406d3f40> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 03:08:01 PM - pika.adapters.blocking_connection - INFO - Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8a406d3f40> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>
2021/11/08 03:08:01 PM - pika.adapters.blocking_connection - INFO - Created channel=1
2021/11/08 03:08:01 PM - pika.adapters.blocking_connection - INFO - Closing connection (200): Normal shutdown
2021/11/08 03:08:01 PM - pika.channel - INFO - Closing channel (200): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8a406d3f40> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 03:08:01 PM - pika.channel - INFO - Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8a406d3f40> params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>>
2021/11/08 03:08:01 PM - pika.connection - INFO - Closing connection (200): 'Normal shutdown'
2021/11/08 03:08:01 PM - pika.adapters.utils.io_services_utils - INFO - Aborting transport connection: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38232), raddr=('167.71.26.87', 5672)>
2021/11/08 03:08:01 PM - pika.adapters.utils.io_services_utils - INFO - _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38232), raddr=('167.71.26.87', 5672)>
2021/11/08 03:08:01 PM - pika.adapters.utils.io_services_utils - INFO - Deactivating transport: state=1; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38232), raddr=('167.71.26.87', 5672)>
2021/11/08 03:08:01 PM - pika.connection - INFO - AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 03:08:01 PM - pika.connection - INFO - Stack terminated due to ConnectionClosedByClient: (200) 'Normal shutdown'
2021/11/08 03:08:01 PM - pika.adapters.utils.io_services_utils - INFO - Closing transport socket and unlinking: state=3; <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.29.170.42', 38232), raddr=('167.71.26.87', 5672)>
2021/11/08 03:08:01 PM - pika.adapters.blocking_connection - INFO - User-initiated close: result=BlockingConnection__OnClosedArgs(connection=<SelectConnection CLOSED transport=None params=<URLParameters host=167.71.26.87 port=5672 virtual_host=/ ssl=False>>, error=ConnectionClosedByClient: (200) 'Normal shutdown')
2021/11/08 03:08:01 PM - Rede1Minuto Server - INFO - (None, None, None)
2021/11/08 05:12:50 PM - uvicorn.error - INFO - Shutting down
2021/11/08 05:12:51 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 05:12:51 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 05:12:51 PM - uvicorn.error - INFO - Finished server process [16581]
2021/11/08 05:13:00 PM - uvicorn.error - INFO - Started server process [22116]
2021/11/08 05:13:00 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 05:13:00 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 05:17:21 PM - uvicorn.error - INFO - Shutting down
2021/11/08 05:17:21 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 05:17:21 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 05:17:21 PM - uvicorn.error - INFO - Finished server process [22116]
2021/11/08 05:17:24 PM - uvicorn.error - INFO - Started server process [23169]
2021/11/08 05:17:24 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 05:17:24 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 05:17:25 PM - uvicorn.error - INFO - Shutting down
2021/11/08 05:17:25 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 05:17:25 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 05:17:25 PM - uvicorn.error - INFO - Finished server process [23169]
2021/11/08 05:17:27 PM - uvicorn.error - INFO - Started server process [23177]
2021/11/08 05:17:27 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 05:17:27 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 05:25:38 PM - uvicorn.error - INFO - Shutting down
2021/11/08 05:25:38 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 05:25:38 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 05:25:38 PM - uvicorn.error - INFO - Finished server process [23177]
2021/11/08 05:25:41 PM - uvicorn.error - INFO - Started server process [24581]
2021/11/08 05:25:41 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 05:25:41 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 05:48:59 PM - uvicorn.error - INFO - Shutting down
2021/11/08 05:49:00 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 05:49:00 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 05:49:00 PM - uvicorn.error - INFO - Finished server process [24581]
2021/11/08 05:49:03 PM - uvicorn.error - INFO - Started server process [30575]
2021/11/08 05:49:03 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 05:49:03 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:12:24 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:12:25 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:12:25 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:12:25 PM - uvicorn.error - INFO - Finished server process [30575]
2021/11/08 06:15:02 PM - uvicorn.error - INFO - Started server process [4571]
2021/11/08 06:15:02 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:15:02 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:17:02 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:17:02 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:17:02 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:17:02 PM - uvicorn.error - INFO - Finished server process [4571]
2021/11/08 06:17:05 PM - uvicorn.error - INFO - Started server process [4887]
2021/11/08 06:17:05 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:17:05 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:17:07 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:17:07 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:17:07 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:17:07 PM - uvicorn.error - INFO - Finished server process [4887]
2021/11/08 06:17:10 PM - uvicorn.error - INFO - Started server process [4945]
2021/11/08 06:17:10 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:17:10 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:20:07 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:20:07 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:20:07 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:20:07 PM - uvicorn.error - INFO - Finished server process [4945]
2021/11/08 06:20:09 PM - uvicorn.error - INFO - Started server process [5421]
2021/11/08 06:20:09 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:20:09 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:21:20 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:21:20 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:21:20 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:21:20 PM - uvicorn.error - INFO - Finished server process [5421]
2021/11/08 06:21:22 PM - uvicorn.error - INFO - Started server process [6824]
2021/11/08 06:21:22 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:21:22 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:35:28 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:35:28 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:35:28 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:35:28 PM - uvicorn.error - INFO - Finished server process [6824]
2021/11/08 06:35:31 PM - uvicorn.error - INFO - Started server process [10417]
2021/11/08 06:35:31 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:35:31 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:44:17 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:44:17 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:44:17 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:44:17 PM - uvicorn.error - INFO - Finished server process [10417]
2021/11/08 06:44:21 PM - uvicorn.error - INFO - Started server process [12029]
2021/11/08 06:44:21 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:44:21 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 06:45:27 PM - uvicorn.error - INFO - Shutting down
2021/11/08 06:45:27 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 06:45:27 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 06:45:27 PM - uvicorn.error - INFO - Finished server process [12029]
2021/11/08 06:45:29 PM - uvicorn.error - INFO - Started server process [12394]
2021/11/08 06:45:29 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 06:45:29 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 09:39:00 PM - uvicorn.error - INFO - Shutting down
2021/11/08 09:39:02 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 09:39:02 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 09:39:02 PM - uvicorn.error - INFO - Finished server process [12394]
2021/11/08 09:39:27 PM - uvicorn.error - INFO - Started server process [14293]
2021/11/08 09:39:27 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 09:39:27 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 09:44:36 PM - uvicorn.error - INFO - Shutting down
2021/11/08 09:44:36 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 09:44:36 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 09:44:36 PM - uvicorn.error - INFO - Finished server process [14293]
2021/11/08 09:44:39 PM - uvicorn.error - INFO - Started server process [14829]
2021/11/08 09:44:39 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 09:44:39 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 09:47:36 PM - uvicorn.error - INFO - Shutting down
2021/11/08 09:47:36 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 09:47:36 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 09:47:36 PM - uvicorn.error - INFO - Finished server process [14829]
2021/11/08 09:47:39 PM - uvicorn.error - INFO - Started server process [15329]
2021/11/08 09:47:39 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 09:47:39 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 09:48:56 PM - uvicorn.error - INFO - Shutting down
2021/11/08 09:48:56 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 09:48:56 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 09:48:56 PM - uvicorn.error - INFO - Finished server process [15329]
2021/11/08 09:48:59 PM - uvicorn.error - INFO - Started server process [17408]
2021/11/08 09:48:59 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 09:48:59 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:16:22 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:16:23 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:16:23 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:16:23 PM - uvicorn.error - INFO - Finished server process [17408]
2021/11/08 10:16:27 PM - uvicorn.error - INFO - Started server process [19903]
2021/11/08 10:16:27 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:16:27 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:16:44 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:16:44 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:16:44 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:16:44 PM - uvicorn.error - INFO - Finished server process [19903]
2021/11/08 10:16:46 PM - uvicorn.error - INFO - Started server process [19909]
2021/11/08 10:16:46 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:16:46 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:27:41 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:27:41 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:27:41 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:27:41 PM - uvicorn.error - INFO - Finished server process [19909]
2021/11/08 10:27:43 PM - uvicorn.error - INFO - Started server process [22287]
2021/11/08 10:27:43 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:27:43 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:27:44 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:27:44 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:27:44 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:27:44 PM - uvicorn.error - INFO - Finished server process [22287]
2021/11/08 10:27:46 PM - uvicorn.error - INFO - Started server process [22291]
2021/11/08 10:27:46 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:27:46 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:34:46 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:34:46 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:34:46 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:34:46 PM - uvicorn.error - INFO - Finished server process [22291]
2021/11/08 10:34:49 PM - uvicorn.error - INFO - Started server process [23446]
2021/11/08 10:34:49 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:34:49 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:34:53 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:34:54 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:34:54 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:34:54 PM - uvicorn.error - INFO - Finished server process [23446]
2021/11/08 10:34:56 PM - uvicorn.error - INFO - Started server process [23450]
2021/11/08 10:34:56 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:34:56 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:40:43 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:40:43 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:40:44 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:40:44 PM - uvicorn.error - INFO - Finished server process [23450]
2021/11/08 10:40:46 PM - uvicorn.error - INFO - Started server process [25274]
2021/11/08 10:40:46 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:40:46 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:48:16 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:48:16 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:48:16 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:48:16 PM - uvicorn.error - INFO - Finished server process [25274]
2021/11/08 10:48:20 PM - uvicorn.error - INFO - Started server process [27477]
2021/11/08 10:48:20 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:48:20 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:49:24 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:49:24 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:49:24 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:49:24 PM - uvicorn.error - INFO - Finished server process [27477]
2021/11/08 10:49:26 PM - uvicorn.error - INFO - Started server process [27731]
2021/11/08 10:49:26 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:49:26 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:49:26 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:49:27 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:49:27 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:49:27 PM - uvicorn.error - INFO - Finished server process [27731]
2021/11/08 10:49:29 PM - uvicorn.error - INFO - Started server process [27735]
2021/11/08 10:49:29 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:49:29 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 10:59:26 PM - uvicorn.error - INFO - Shutting down
2021/11/08 10:59:26 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 10:59:26 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 10:59:26 PM - uvicorn.error - INFO - Finished server process [27735]
2021/11/08 10:59:29 PM - uvicorn.error - INFO - Started server process [30538]
2021/11/08 10:59:29 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 10:59:29 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 11:17:18 PM - uvicorn.error - INFO - Shutting down
2021/11/08 11:17:18 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 11:17:18 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 11:17:18 PM - uvicorn.error - INFO - Finished server process [30538]
2021/11/08 11:17:21 PM - uvicorn.error - INFO - Started server process [31695]
2021/11/08 11:17:21 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 11:17:21 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 11:17:22 PM - uvicorn.error - INFO - Shutting down
2021/11/08 11:17:22 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 11:17:22 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 11:17:22 PM - uvicorn.error - INFO - Finished server process [31695]
2021/11/08 11:17:24 PM - uvicorn.error - INFO - Started server process [31699]
2021/11/08 11:17:24 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 11:17:24 PM - uvicorn.error - INFO - Application startup complete.
2021/11/08 11:25:27 PM - uvicorn.error - INFO - Shutting down
2021/11/08 11:25:27 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/08 11:25:27 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/08 11:25:27 PM - uvicorn.error - INFO - Finished server process [31699]
2021/11/08 11:25:30 PM - uvicorn.error - INFO - Started server process [731]
2021/11/08 11:25:30 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/08 11:25:30 PM - uvicorn.error - INFO - Application startup complete.
2021/11/09 12:45:34 PM - uvicorn.error - INFO - Shutting down
2021/11/09 12:45:35 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/09 12:45:36 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/09 12:45:36 PM - uvicorn.error - INFO - Finished server process [731]
2021/11/10 05:00:55 PM - uvicorn.error - INFO - Started server process [1519]
2021/11/10 05:00:55 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:00:55 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:01:07 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:01:07 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:01:07 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:01:07 PM - uvicorn.error - INFO - Finished server process [1519]
2021/11/10 05:01:09 PM - uvicorn.error - INFO - Started server process [1524]
2021/11/10 05:01:09 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:01:09 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:14:41 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:14:41 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:14:41 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:14:41 PM - uvicorn.error - INFO - Finished server process [1524]
2021/11/10 05:14:43 PM - uvicorn.error - INFO - Started server process [3476]
2021/11/10 05:14:43 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:14:43 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:34:23 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:34:24 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:34:24 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:34:24 PM - uvicorn.error - INFO - Finished server process [3476]
2021/11/10 05:34:26 PM - uvicorn.error - INFO - Started server process [5300]
2021/11/10 05:34:26 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:34:26 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:34:50 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:34:51 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:34:51 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:34:51 PM - uvicorn.error - INFO - Finished server process [5300]
2021/11/10 05:34:53 PM - uvicorn.error - INFO - Started server process [5661]
2021/11/10 05:34:53 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:34:53 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:37:07 PM - Rede1Minuto Server - ERROR - (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'"), <traceback object at 0x7f12ce538d80>)
2021/11/10 05:37:07 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/boaro/projects/r1mmensageria/./app.py", line 118, in register
    result["command sql"] = command_sql
UnboundLocalError: local variable 'command_sql' referenced before assignment
2021/11/10 05:38:16 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:38:16 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:38:16 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:38:16 PM - uvicorn.error - INFO - Finished server process [5661]
2021/11/10 05:38:19 PM - uvicorn.error - INFO - Started server process [6047]
2021/11/10 05:38:19 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:38:19 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:38:26 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:38:27 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:38:27 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:38:27 PM - uvicorn.error - INFO - Finished server process [6047]
2021/11/10 05:38:29 PM - uvicorn.error - INFO - Started server process [6051]
2021/11/10 05:38:29 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:38:29 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:39:08 PM - Rede1Minuto Server - ERROR - (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'"), <traceback object at 0x7f5af7227f80>)
2021/11/10 05:39:08 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/boaro/projects/r1mmensageria/./app.py", line 118, in register
    if command_sql is not None:
UnboundLocalError: local variable 'command_sql' referenced before assignment
2021/11/10 05:40:17 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:40:17 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:40:17 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:40:17 PM - uvicorn.error - INFO - Finished server process [6051]
2021/11/10 05:40:20 PM - uvicorn.error - INFO - Started server process [6084]
2021/11/10 05:40:20 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:40:20 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:40:33 PM - Rede1Minuto Server - ERROR - (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'"), <traceback object at 0x7f3c759edc00>)
2021/11/10 05:40:33 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'wrapper_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/10 05:43:14 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:43:14 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:43:14 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:43:14 PM - uvicorn.error - INFO - Finished server process [6084]
2021/11/10 05:43:16 PM - uvicorn.error - INFO - Started server process [6511]
2021/11/10 05:43:16 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:43:16 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:44:23 PM - Rede1Minuto Server - ERROR - (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'"), <traceback object at 0x7f3dc4fce1c0>)
2021/11/10 05:44:23 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'wrapper_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/10 05:44:41 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:44:41 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:44:41 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:44:41 PM - uvicorn.error - INFO - Finished server process [6511]
2021/11/10 05:44:50 PM - uvicorn.error - INFO - Started server process [6517]
2021/11/10 05:44:50 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:44:50 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:44:58 PM - Rede1Minuto Server - ERROR - (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'"), <traceback object at 0x7ffa0f602dc0>)
2021/11/10 05:44:58 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'wrapper_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/10 05:46:57 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:46:57 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:46:57 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:46:57 PM - uvicorn.error - INFO - Finished server process [6517]
2021/11/10 05:47:01 PM - uvicorn.error - INFO - Started server process [6898]
2021/11/10 05:47:01 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:47:01 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:47:15 PM - Rede1Minuto Server - ERROR - (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'"), <traceback object at 0x7f3f79156e00>)
2021/11/10 05:47:15 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'wrapper_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/10 05:50:14 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:50:14 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 05:50:14 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 05:50:14 PM - uvicorn.error - INFO - Finished server process [6898]
2021/11/10 05:50:16 PM - uvicorn.error - INFO - Started server process [7272]
2021/11/10 05:50:16 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 05:50:16 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 05:50:25 PM - Rede1Minuto Server - ERROR - (<class 'TypeError'>, TypeError("unsupported operand type(s) for +: 'NoneType' and 'str'"), <traceback object at 0x7f38df121b80>)
2021/11/10 05:50:25 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 142, in jsonable_encoder
    return jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'wrapper_descriptor' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/10 05:56:40 PM - uvicorn.error - INFO - Shutting down
2021/11/10 05:56:41 PM - uvicorn.error - INFO - Waiting for connections to close. (CTRL+C to force quit)
2021/11/10 05:57:19 PM - uvicorn.error - INFO - Waiting for background tasks to complete. (CTRL+C to force quit)
2021/11/10 06:00:45 PM - uvicorn.error - INFO - Finished server process [7272]
2021/11/10 06:01:41 PM - uvicorn.error - INFO - Started server process [8098]
2021/11/10 06:01:41 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:01:41 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:04:27 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:04:27 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:04:27 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:04:27 PM - uvicorn.error - INFO - Finished server process [8098]
2021/11/10 06:04:29 PM - uvicorn.error - INFO - Started server process [8475]
2021/11/10 06:04:29 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:04:29 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:07:24 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:07:24 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:07:24 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:07:24 PM - uvicorn.error - INFO - Finished server process [8475]
2021/11/10 06:07:26 PM - uvicorn.error - INFO - Started server process [8855]
2021/11/10 06:07:26 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:07:26 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:13:02 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:13:02 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:13:02 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:13:02 PM - uvicorn.error - INFO - Finished server process [8855]
2021/11/10 06:13:08 PM - uvicorn.error - INFO - Started server process [8860]
2021/11/10 06:13:08 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:13:08 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:16:31 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:16:31 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:16:31 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:16:31 PM - uvicorn.error - INFO - Finished server process [8860]
2021/11/10 06:16:34 PM - uvicorn.error - INFO - Started server process [9236]
2021/11/10 06:16:34 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:16:34 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:16:41 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:16:41 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:16:41 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:16:41 PM - uvicorn.error - INFO - Finished server process [9236]
2021/11/10 06:16:44 PM - uvicorn.error - INFO - Started server process [9241]
2021/11/10 06:16:44 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:16:44 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:16:55 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:16:55 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:16:55 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:16:55 PM - uvicorn.error - INFO - Finished server process [9241]
2021/11/10 06:17:05 PM - uvicorn.error - INFO - Started server process [9246]
2021/11/10 06:17:05 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:17:05 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:17:10 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:17:10 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:17:10 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:17:10 PM - uvicorn.error - INFO - Finished server process [9246]
2021/11/10 06:17:13 PM - uvicorn.error - INFO - Started server process [9252]
2021/11/10 06:17:13 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:17:13 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:19:09 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:19:09 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:19:09 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:19:09 PM - uvicorn.error - INFO - Finished server process [9252]
2021/11/10 06:19:14 PM - uvicorn.error - INFO - Started server process [9257]
2021/11/10 06:19:14 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/10 06:19:14 PM - uvicorn.error - INFO - Application startup complete.
2021/11/10 06:26:52 PM - uvicorn.error - INFO - Shutting down
2021/11/10 06:26:52 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/10 06:26:52 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/10 06:26:52 PM - uvicorn.error - INFO - Finished server process [9257]
2021/11/11 09:24:50 AM - uvicorn.error - INFO - Started server process [13378]
2021/11/11 09:24:50 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 09:24:50 AM - uvicorn.error - INFO - Application startup complete.
2021/11/11 09:25:04 AM - uvicorn.error - INFO - Shutting down
2021/11/11 09:25:04 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 09:25:04 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 09:25:04 AM - uvicorn.error - INFO - Finished server process [13378]
2021/11/11 09:25:06 AM - uvicorn.error - INFO - Started server process [13384]
2021/11/11 09:25:06 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 09:25:06 AM - uvicorn.error - INFO - Application startup complete.
2021/11/11 10:28:56 AM - uvicorn.error - INFO - Shutting down
2021/11/11 10:28:56 AM - uvicorn.error - INFO - Finished server process [13384]
2021/11/11 10:32:06 AM - uvicorn.error - INFO - Started server process [15141]
2021/11/11 10:32:06 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 10:32:06 AM - uvicorn.error - INFO - Application startup complete.
2021/11/11 10:33:03 AM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/11 10:33:03 AM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/11 11:47:38 AM - uvicorn.error - INFO - Shutting down
2021/11/11 11:47:38 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 11:47:38 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 11:47:38 AM - uvicorn.error - INFO - Finished server process [15141]
2021/11/11 12:51:31 PM - uvicorn.error - INFO - Started server process [22693]
2021/11/11 12:51:31 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 12:51:31 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 12:51:38 PM - uvicorn.error - INFO - Shutting down
2021/11/11 12:51:38 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 12:51:38 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 12:51:38 PM - uvicorn.error - INFO - Finished server process [22693]
2021/11/11 12:51:42 PM - uvicorn.error - INFO - Started server process [22696]
2021/11/11 12:51:42 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 12:51:42 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 12:51:59 PM - uvicorn.error - INFO - Shutting down
2021/11/11 12:51:59 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 12:51:59 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 12:51:59 PM - uvicorn.error - INFO - Finished server process [22696]
2021/11/11 12:52:01 PM - uvicorn.error - INFO - Started server process [23071]
2021/11/11 12:52:01 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 12:52:01 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 12:52:02 PM - uvicorn.error - INFO - Shutting down
2021/11/11 12:52:02 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 12:52:02 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 12:52:02 PM - uvicorn.error - INFO - Finished server process [23071]
2021/11/11 12:52:05 PM - uvicorn.error - INFO - Started server process [23075]
2021/11/11 12:52:05 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 12:52:05 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 12:54:24 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/11 12:54:24 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/11 12:56:02 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/11 12:56:02 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/11 12:58:27 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/11 12:58:27 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/11 01:00:56 PM - uvicorn.error - INFO - Shutting down
2021/11/11 01:00:56 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 01:00:56 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 01:00:56 PM - uvicorn.error - INFO - Finished server process [23075]
2021/11/11 01:00:59 PM - uvicorn.error - INFO - Started server process [23509]
2021/11/11 01:00:59 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 01:00:59 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 01:01:08 PM - uvicorn.error - INFO - Shutting down
2021/11/11 01:01:08 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 01:01:08 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 01:01:08 PM - uvicorn.error - INFO - Finished server process [23509]
2021/11/11 01:01:11 PM - uvicorn.error - INFO - Started server process [23514]
2021/11/11 01:01:11 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 01:01:11 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 01:01:20 PM - uvicorn.error - INFO - Shutting down
2021/11/11 01:01:20 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 01:01:20 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 01:01:20 PM - uvicorn.error - INFO - Finished server process [23514]
2021/11/11 01:01:24 PM - uvicorn.error - INFO - Started server process [23517]
2021/11/11 01:01:24 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 01:01:24 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 01:01:37 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/11 01:01:37 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/11 01:56:37 PM - uvicorn.error - INFO - Shutting down
2021/11/11 01:56:37 PM - uvicorn.error - INFO - Waiting for connections to close. (CTRL+C to force quit)
2021/11/11 01:59:00 PM - uvicorn.error - INFO - Finished server process [23517]
2021/11/11 01:59:48 PM - uvicorn.error - INFO - Started server process [28416]
2021/11/11 01:59:48 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 01:59:48 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 02:03:11 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/11 02:03:11 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/11 02:03:11 PM - Rede1Minuto Server - ERROR - (<class 'sqlalchemy.exc.OperationalError'>, OperationalError('(pymysql.err.OperationalError) (1054, "Unknown column \'idLockerCategoria\' in \'field list\'")'), <traceback object at 0x7f9e21624580>)
2021/11/11 02:03:11 PM - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 209, in app
    response_data = await serialize_response(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 137, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 90, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 104, in jsonable_encoder
    jsonable_encoder(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/encoders.py", line 141, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'traceback' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
2021/11/11 02:07:42 PM - uvicorn.error - INFO - Shutting down
2021/11/11 02:07:42 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 02:07:42 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 02:07:42 PM - uvicorn.error - INFO - Finished server process [28416]
2021/11/11 02:07:44 PM - uvicorn.error - INFO - Started server process [29429]
2021/11/11 02:07:44 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 02:07:44 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 02:08:04 PM - uvicorn.error - INFO - Shutting down
2021/11/11 02:08:04 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 02:08:04 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 02:08:04 PM - uvicorn.error - INFO - Finished server process [29429]
2021/11/11 02:08:07 PM - uvicorn.error - INFO - Started server process [29434]
2021/11/11 02:08:07 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 02:08:07 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 02:08:10 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/11 02:08:10 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/11 03:49:32 PM - uvicorn.error - INFO - Shutting down
2021/11/11 03:49:32 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 03:49:32 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 03:49:32 PM - uvicorn.error - INFO - Finished server process [29434]
2021/11/11 03:49:44 PM - uvicorn.error - INFO - Started server process [1943]
2021/11/11 03:49:44 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 03:49:44 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 03:50:09 PM - uvicorn.error - INFO - Shutting down
2021/11/11 03:50:09 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 03:50:09 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 03:50:09 PM - uvicorn.error - INFO - Finished server process [1943]
2021/11/11 04:02:00 PM - uvicorn.error - INFO - Started server process [4870]
2021/11/11 04:02:00 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 04:02:00 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 04:11:08 PM - uvicorn.error - INFO - Shutting down
2021/11/11 04:11:08 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 04:11:08 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 04:11:08 PM - uvicorn.error - INFO - Finished server process [4870]
2021/11/11 04:11:11 PM - uvicorn.error - INFO - Started server process [7090]
2021/11/11 04:11:11 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 04:11:11 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 04:14:01 PM - uvicorn.error - INFO - Shutting down
2021/11/11 04:14:01 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 04:14:01 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 04:14:01 PM - uvicorn.error - INFO - Finished server process [7090]
2021/11/11 04:17:19 PM - uvicorn.error - INFO - Started server process [8888]
2021/11/11 04:17:19 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 04:17:19 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 04:17:21 PM - uvicorn.error - INFO - Shutting down
2021/11/11 04:17:21 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 04:17:21 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 04:17:21 PM - uvicorn.error - INFO - Finished server process [8888]
2021/11/11 04:17:23 PM - uvicorn.error - INFO - Started server process [8892]
2021/11/11 04:17:23 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 04:17:23 PM - uvicorn.error - INFO - Application startup complete.
2021/11/11 04:29:27 PM - uvicorn.error - INFO - Shutting down
2021/11/11 04:29:27 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/11 04:29:27 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/11 04:29:27 PM - uvicorn.error - INFO - Finished server process [8892]
2021/11/11 04:29:29 PM - uvicorn.error - INFO - Started server process [9518]
2021/11/11 04:29:29 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/11 04:29:29 PM - uvicorn.error - INFO - Application startup complete.
2021/11/12 09:04:41 AM - uvicorn.error - INFO - Shutting down
2021/11/12 09:04:42 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/12 09:04:42 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/12 09:04:42 AM - uvicorn.error - INFO - Finished server process [9518]
2021/11/12 09:04:56 AM - uvicorn.error - INFO - Started server process [13913]
2021/11/12 09:04:56 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/12 09:04:56 AM - uvicorn.error - INFO - Application startup complete.
2021/11/12 12:43:07 PM - uvicorn.error - INFO - Started server process [919]
2021/11/12 12:43:07 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/12 12:43:07 PM - uvicorn.error - INFO - Application startup complete.
2021/11/12 12:43:59 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/12 12:43:59 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/12 12:45:17 PM - uvicorn.error - INFO - Shutting down
2021/11/12 12:45:17 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/12 12:45:17 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/12 12:45:17 PM - uvicorn.error - INFO - Finished server process [919]
2021/11/12 12:45:19 PM - uvicorn.error - INFO - Started server process [4101]
2021/11/12 12:45:19 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/12 12:45:19 PM - uvicorn.error - INFO - Application startup complete.
2021/11/12 12:46:22 PM - Rede1Minuto Server - INFO - Consulta ao Catalogo de Estações Lockers
2021/11/12 12:46:22 PM - Rede1Minuto Server - INFO - Usuário que fez a solicitação: e5b1632f-9fdc-48b3-91cb-8bedb70b6926
2021/11/12 01:04:37 PM - uvicorn.error - INFO - Shutting down
2021/11/12 01:04:37 PM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/12 01:04:37 PM - uvicorn.error - INFO - Application shutdown complete.
2021/11/12 01:04:37 PM - uvicorn.error - INFO - Finished server process [4101]
2021/11/12 01:04:39 PM - uvicorn.error - INFO - Started server process [6389]
2021/11/12 01:04:39 PM - uvicorn.error - INFO - Waiting for application startup.
2021/11/12 01:04:39 PM - uvicorn.error - INFO - Application startup complete.
2021/11/13 10:50:05 AM - uvicorn.error - INFO - Shutting down
2021/11/13 10:50:05 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/13 10:50:05 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/13 10:50:05 AM - uvicorn.error - INFO - Finished server process [6389]
2021/11/13 10:50:08 AM - uvicorn.error - INFO - Started server process [9098]
2021/11/13 10:50:08 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/13 10:50:08 AM - uvicorn.error - INFO - Application startup complete.
2021/11/13 10:56:06 AM - uvicorn.error - INFO - Shutting down
2021/11/13 10:56:06 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/13 10:56:06 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/13 10:56:06 AM - uvicorn.error - INFO - Finished server process [9098]
2021/11/13 10:56:08 AM - uvicorn.error - INFO - Started server process [12275]
2021/11/13 10:56:08 AM - uvicorn.error - INFO - Waiting for application startup.
2021/11/13 10:56:08 AM - uvicorn.error - INFO - Application startup complete.
2021/11/14 09:21:42 AM - uvicorn.error - INFO - Shutting down
2021/11/14 09:21:43 AM - uvicorn.error - INFO - Waiting for application shutdown.
2021/11/14 09:21:43 AM - uvicorn.error - INFO - Application shutdown complete.
2021/11/14 09:21:43 AM - uvicorn.error - INFO - Finished server process [12275]
